FROM ubuntu:22.04

# Install nested dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    unzip \
    ca-certificates \
    build-essential \
    libssl-dev \
    pkg-config \
    libclang-dev \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Rust
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# Install SUI via devnet branch
RUN cargo install --locked --git https://github.com/MystenLabs/sui.git --branch testnet sui --features tracing

RUN rustup update stable

# Install Node.js 22 
RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
    && apt-get install -y nodejs \
    && npm install -g npm



# Sui CLI'yi PATH'e ekle
ENV PATH="/root/.cargo/bin:${PATH}"

